version: "3.3"
services:

  post:
    image: timgnh/us:v1.0.0
    restart: always
    depends_on:
      - "db-postgres"
    ports:
      - "4000-4999:4000-4999"


  db-postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: US
      POSTGRES_USER: US
      POSTGRES_DB: us.db.dev
    ports:
      - "5432:5432"

