version: "3.3"
services:

  post:
    build: .
    restart: always
    depends_on:
      - "db-postgres"
    ports:
      - "4000-4999:4000-4999"
    stdin_open: true
    tty: true

  db-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: US
      POSTGRES_USER: US
      POSTGRES_DB: us.db.dev
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
